### ISSUE TITLE
Throw http 401 rather than redirect to 'login'

### ISSUE THREAD

**Issue by nover** [jeremykendall/slim-auth#11]
Hi!

I'm currently using SLIM 2 for creating a rest api which needs authentication and authorization - and decided to give your plugin a spin.

However, I find it suboptimal that the authentication performs a redirect to 'login' when the user is not logged in - it would be much nicer if it just returned a 401, to show the consumers of the API that authentication is required.

Perhaps it could be configurable in the Bootstrapper? Like, adding an configuration array as a 4'th optional argument

```php
$acl = new \My\ApiAcl();
$authBootstrap = new Bootstrap($app, $adapter, $acl, array(
   'disableAuthRedirect'  => true
));
$authBootstrap->bootstrap();
```

Or similar :)

**Comment by jeremykendall** [comment]
@nover FYI, I'm working on this as a BC breaking change for the first beta version. It's gonna be really nice. Thanks for the feature request!

**Comment by nover** [comment]
@jeremykendall Great! Glad to hear that - and sorry that I never got around to looking at the issue as promised.

**Comment by jeremykendall** [comment]
@nover No worries! It only took me 1/4 years :-)

I'll close this once I've released 0.0.7-alpha.

**Comment by LorenzBischof** [comment]
How would I add the old behavior again?

**Comment by jeremykendall** [comment]
@Lorenzbi You don't. I decided I @nover's idea was so much better, and more appropriate, that I pulled out the old behavior entirely.

The new way to handle unauthorized requests is with the Slim custom error handler, like so:

``` php
// Handle the possible 403 the middleware can throw
$app->error(function (\Exception $e) use ($app) {
    if ($e instanceof HttpForbiddenException) {
        return $app->render('403.twig', array('e' => $e), 403);
    }
    if ($e instanceof HttpUnauthorizedException) {
        return $app->redirectTo('login');
    }
    // You should handle other exceptions here, not throw them
    throw $e;
});
```

**Comment by cGuille** [comment]
Hello!

I just used a slightly customized version of the custom error handler you provided. I wanted to give you some feedback about this choice.

I was disappointed to see that, since the Slim custom error handler is ignored in debug mode, I could not get login redirections in debug mode. I think this is bad: you get different behaviours depending on whether you are in debug mode or not. Moreover, the fact that the custom error handler is ignored in debug mode lets me think that its intended purpose is only to manage the rendering of errors, not really handling them with some kind of business logic.

I don't know Slim well, but I do not think it provides a clean way to handle the errors thrown by a middleware. So maybe unauthorized requests should not be considered as errors (and thus not result in the throwing of an uncaught exception in the auth middleware).

Could we imagine an optional handler that we would pass to slim auth, telling what to do with unauthorized requests? It would throw an `HttpUnauthorizedException` by default but this behaviour would be customizable.
