### ISSUE TITLE
Cannot use object of type stdClass as array

### ISSUE THREAD

**Issue by Lorenzbi** [jeremykendall/slim-auth#13]
Hello,

I am receiving following error:

127.0.0.1:52605 [200]: /login - Cannot use object of type stdClass as array in /.../vendor/jeremykendall/slim-auth/src/JeremyKendall/Slim/Auth/Adapter/Db/PdoAdapter.php on line 90

I am using following code:

```
$adapter = new PdoAdapter(
    $db, 
    'Students', 
    'email', 
    'password', 
    new PasswordValidator()
);

$acl = new \Mini\Acl();
$authBootstrap = new Bootstrap($app, $adapter, $acl);
$authBootstrap->bootstrap();
$app->add(new \Slim\Middleware\SessionCookie());
```

I also added the cookies config and example route. Am I doing something wrong?

**Comment by jeremykendall** [comment]
It seems you have `\PDO::ATTR_DEFAULT_FETCH_MODE` set to `\PDO::FETCH_OBJ` rather than `\PDO::FETCH_ASSOC` (or one of the other [fetch modes](http://php.net/manual/en/pdo.setattribute.php) that includes an associative array).

A quick fix for you might be to choose `\PDO::FETCH_LAZY` for now, but this is definitely an oversight on my part. I need to set a fetch mode in the PdoAdapter. 

Thanks for the bug report.

**Comment by Lorenzbi** [comment]
Thank you very much!

**Comment by jeremykendall** [comment]
@Lorenzbi You're welcome!
