### ISSUE TITLE
Route for login

### ISSUE THREAD

**Issue by marvinosswald** [jeremykendall/slim-auth#22]
As I'm using slim only for my api I would like to have my login also nested in the url like that:
`/api/v1/login`

implemented like that:

``` php
// General API group
$app->group(
    '/api',
    function () use ($app, $log) {

        // Common to all sub routes

        // Get contacts
        $app->get('/', function () {
          echo stripslashes(file_get_contents("docs/index.html"));
        });

        // Group for API Version 1
        $app->group(
            '/v1',
            // API Methods
            function () use ($app, $log) {

                $app->post(
                  '/login',
                  function () use ($app,$log){
                    $json = $app->request->getBody();
                    $result = $app->authenticator->authenticate($json->username, $json->password);
                    if ($result->isValid()) {
                      echo json_encode(true, JSON_PRETTY_PRINT);
                    } else {
                      echo json_encode(false, JSON_PRETTY_PRINT);
                    }
                  }
                );
```

But slim-auth says it can't find a login route..
And another question I would like to use a token system so giving the user a token back after login which a middleware should check..

Cheers Marv

**Comment by jeremykendall** [comment]
Modify your login route and use the [route naming feature](http://docs.slimframework.com/routing/names/) to name the route `login`.  That might cause a new failure since the redirect expects the login route to be a `GET` route, providing a form for the user to login.

Since this is an api and not a website with a UI, you might want to use my [Query Auth](https://github.com/jeremykendall/query-auth) library instead of this one. Query Auth provides "Signature generation and validation for REST API query authentication." for the Slim Framework.

**Comment by marvinosswald** [comment]
Man that was quick.. awesome :+1:  

Mh yeah seems to be a better option for me but it doesn't have an own implementation for database use, does it ?

**Comment by jeremykendall** [comment]
>  ... it doesn't have an own implementation for database use, does it ?

No, it doesn't. You'll need to add an api key and api secret column to your database, query on the api key they send over, and then do the validation.

There's a sample implementation that might help make it clearer. See https://github.com/jeremykendall/query-auth-impl

**Comment by marvinosswald** [comment]
Okay thanks. I'm just thinking out loud here but would love to here some advice from you on this one:

User Login (with credentials) ---> response with apikey --> user uses apikey for communication with api (I look up the delivered api key in my table to verify it as middleware)--> user logout --> I delete the apikey from my apikey table... 

+
I let the apikey expire

Thanks in advance

**Comment by jeremykendall** [comment]
No reason why you couldn't do that. You'd just generate a new API key on login. The problem comes when the user puts that API key in use. If the only calls requiring the key are internal to your app (the user never even knows about the key), then no problem. Otherwise your users would have to pick up that new key every time they log in, plug it into their third party app, and start making requests.

**Comment by jeremykendall** [comment]
Closing, but happy to continue any discussion.
