### ISSUE TITLE
Session issues

### ISSUE THREAD

**Issue by Siim** [jeremykendall/slim-auth#9]
Hi.

I followed your README to setup slim-auth. Now I have some issues with session persistence - I created admin user and I can log in with it. 

However if I try to use some protected routing, the session could not remember that user is logged in.

I followed the code and tried to understand, whats wrong. So I found out that if AuthorizationMiddleware is initialized, it will get $auth and $acl objects. In AuthorizationMiddleware's constructor function the $auth->getStorage()->read() will reveal the correct session data. Now if I debugged the AuthorizationMiddleware call() method then $this->auth->getStorage()->read() is empty. I cannot figure out what's wrong with it.

**Comment by jeremykendall** [comment]
Hey @Siim, 

I still have no idea why you experienced the issues you experienced, but since Slim 2.6.0 I was experiencing something similar. I've dropped the recommendation to use Slim's SessionCookie middleware and done some refactoring around Zend Session. Check out the latest release for more: [0.0.7-alpha](https://github.com/jeremykendall/slim-auth/releases/tag/0.0.7-alpha).
